apiVersion: 1

datasources:
- name: influx
  type: influxdb
  access: proxy
  url: http://influxdb:8086
  password:
  user:
  database:
  basicAuth: false
  basicAuthUser:
  basicAuthPassword:
  withCredentials:
  isDefault: true
  jsonData:
    tlsAuth: false
    tlsAuthWithCACert: false
    httpHeaderName1: 'Authorization'
  secureJsonData:
    tlsCACert: ""
    tlsClientCert: ""
    tlsClientKey: ""
    httpHeaderValue1: 'Token test'
  version: 1
  editable: true
