name: Main

on: push

jobs:
  release:
    name: release ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@master

      - name: Compile and release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
